### ISSUE TITLE
GitHub Actions 自动构建

### ISSUE THREAD

**Issue by taoky** [ustclug/liimstrap#6]
额外可能需要注意的地方：
- 密码。如果构建产物最终公开，需要参考 https://wiki.archlinux.org/title/SHA_password_hashes 检查并提升密码强度。

**Comment by iBug** [comment]
关于密码由 liims-monitor 下发的技术调研：

- 服务端：
	- Go 语言自带的 TLS 库可以实现 HTTPS server，也可以前面套个 nginx
	- 可以用 `mkpasswd` 生成 hash 后的密码，此处可以直接 `exec.Command`，也可以用 [`mkpasswd.go`](https://github.com/myENA/mkpasswd/blob/master/mkpasswd.go) 这样内置在 Go 程序里的解决方案
- 查询机：`chpasswd -e` 可以将 hash 后的密码直接设置
- 查询密码的鉴权：客户端 IP 地址为 `127.0.0.1` 或 `::1`，同时排除 nginx（例如要求 `X-Forwarded-For` 不存在）
